#!/usr/bin/env python3
"""Install and remove the small shell integration owned by codex-flow."""

from __future__ import annotations

import argparse
import re
import shlex
from pathlib import Path


BEGIN = "# >>> codex-flow >>>"
END = "# <<< codex-flow <<<"
BLOCK_RE = re.compile(
    rf"(?ms)^{re.escape(BEGIN)}[ \t]*\n.*?^{re.escape(END)}[ \t]*(?:\n|$)"
)


def read_text(path: Path) -> str:
    try:
        return path.read_text()
    except FileNotFoundError:
        return ""


def remove_blocks(text: str) -> str:
    return BLOCK_RE.sub("", text)


def write_if_changed(path: Path, text: str) -> None:
    if read_text(path) == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def state_path(state_dir: Path, name: str) -> Path:
    return state_dir / "shell" / name


def absolute_path(value: str) -> Path:
    return Path(value).expanduser().resolve()


def old_rc_paths(state_dir: Path) -> list[Path]:
    metadata = state_path(state_dir, "rc_paths")
    if not metadata.exists():
        return []
    return [Path(line) for line in metadata.read_text().splitlines() if line]


def shell_rc_paths(shell: str, config_dir: Path) -> list[Path]:
    if shell == "zsh":
        return [config_dir / ".zshrc"]
    if shell == "bash":
        paths = [config_dir / ".bashrc"]
        for name in (".bash_profile", ".bash_login", ".profile"):
            candidate = config_dir / name
            if candidate.exists():
                paths.append(candidate)
                break
        else:
            # A login bash reads one of these files instead of .bashrc. Keep a
            # managed entry point so new login terminals receive the setup.
            paths.append(config_dir / ".bash_profile")
        return paths
    raise ValueError(f"unsupported shell: {shell}")


def make_init(state_dir: Path, shell: str, bin_dir: Path) -> str:
    completion = state_path(state_dir, "codex-flow.zsh" if shell == "zsh" else "codex-flow.bash")
    quoted_bin = shlex.quote(str(bin_dir))
    quoted_completion = shlex.quote(str(completion))
    return f"""#!{'/usr/bin/env zsh' if shell == 'zsh' else '/usr/bin/env bash'}
# Generated by codex-flow. This file is sourced by the managed rc block.
case :${{PATH-}}: in
  *:{quoted_bin}:*) ;;
  *) PATH={quoted_bin}:$PATH ;;
esac
export PATH
source {quoted_completion}
"""


def managed_block(state_dir: Path, shell: str) -> str:
    init = shlex.quote(str(state_path(state_dir, "init.sh")))
    if shell == "bash":
        return (
            f"{BEGIN}\n"
            f"if [ -n \"${{BASH_VERSION:-}}\" ] && [ -r {init} ]; then\n"
            f"  . {init}\n"
            f"fi\n"
            f"{END}\n"
        )
    return f"{BEGIN}\nsource {init}\n{END}\n"


def install(args: argparse.Namespace) -> None:
    state_dir = absolute_path(args.state_dir)
    config_dir = absolute_path(args.config_dir)
    bin_dir = absolute_path(args.bin_dir)
    shell_dir = state_dir / "shell"
    shell_dir.mkdir(parents=True, exist_ok=True)

    # Remove blocks from paths recorded by the previous install first. This
    # also handles an install where the selected shell or config dir changed.
    for path in old_rc_paths(state_dir):
        write_if_changed(path, remove_blocks(read_text(path)))

    rc_paths = shell_rc_paths(args.shell, config_dir)
    init_path = state_path(state_dir, "init.sh")
    write_if_changed(init_path, make_init(state_dir, args.shell, bin_dir))
    init_path.chmod(0o755)
    write_if_changed(state_path(state_dir, "shell"), f"{args.shell}\n")
    write_if_changed(state_path(state_dir, "bin_dir"), f"{bin_dir}\n")

    block = managed_block(state_dir, args.shell)
    for path in rc_paths:
        text = remove_blocks(read_text(path))
        if text and not text.endswith("\n"):
            text += "\n"
        if text and not text.endswith("\n\n"):
            text += "\n"
        write_if_changed(path, text + block)
    write_if_changed(state_path(state_dir, "rc_paths"), "".join(f"{path}\n" for path in rc_paths))


def uninstall(args: argparse.Namespace) -> None:
    state_dir = absolute_path(args.state_dir)
    for path in old_rc_paths(state_dir):
        write_if_changed(path, remove_blocks(read_text(path)))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("install", "uninstall"))
    parser.add_argument("--state-dir", required=True)
    parser.add_argument("--shell", choices=("bash", "zsh"))
    parser.add_argument("--config-dir")
    parser.add_argument("--bin-dir")
    args = parser.parse_args()
    if args.action == "install":
        if not args.config_dir or not args.bin_dir or not args.shell:
            parser.error("install requires --shell, --config-dir, and --bin-dir")
        install(args)
    else:
        uninstall(args)


if __name__ == "__main__":
    main()
